- hosts: master
  gather_facts: yes
  vars_files:
    - cnc_values.yaml
  tasks:
    - name: Validate kubernetes cluster is up
      shell:  kubectl cluster-info | grep master
      register: cluster
      failed_when: false
      ignore_errors: yes

    - name: Check Operating System Version
      shell: cat /etc/os-release | grep -iw version | sed 's/VERSION=//g;s/"//g'
      register: osversion
      ignore_errors: yes

    - name: Check Docker Version
      become: true
      when: cnc_version <= 3.1
      shell: docker version | grep -i -A2 'Server' | grep Version  | awk '{print $2}'
      register: dockerversion
      ignore_errors: yes

    - name: Check Containerd Version
      become: true
      when: cnc_version >= 4.0
      shell: containerd -v | awk '{print $3}'
      register: containerd_version
      ignore_errors: yes

    - name: Check Kubernetes Version
      shell: kubectl get nodes | awk '{print $NF}' | grep -v VERSION
      register: k8sversion
      ignore_errors: yes

    - name: Check Helm Version
      shell: helm version --short | sed 's/v//g;s/\+.*//g'
      register: helmversion
      ignore_errors: yes

    - name: Check Nvidia GPU Operator Toolkit versions
      shell: kubectl get pods --all-namespaces -o=jsonpath="{range .items[*]}{.metadata.name}{'\t'}{.spec.containers[*].image}{'\n'}" | grep toolkit | awk -F':' '{print $2}' | awk -F'-' '{print $1}' | head -n1
      register: nvtoolkit
      ignore_errors: yes

    - name: Check Nvidia K8s Device versions
      shell: kubectl get pods --all-namespaces -o=jsonpath="{range .items[*]}{.metadata.name}{'\t'}{.spec.containers[*].image}{'\n'}" | grep 'k8s-device' | awk -F':' '{print $2}' | head -n1
      register: k8sdevice
      ignore_errors: yes

    - name: Check GPU Operator Nvidia Container Driver versions
      shell: kubectl get pods --all-namespaces -o=jsonpath="{range .items[*]}{.metadata.name}{'\t'}{.spec.containers[*].image}{'\n'}" | grep 'nvidia/driver'  | awk -F':' '{print $2}' | awk -F'-' '{print $1}' | head -n1
      register: nvcdriver
      ignore_errors: yes

    - name: Check GPU Operator Nvidia DGCM Exporter Versions
      shell: kubectl get pods --all-namespaces -o=jsonpath="{range .items[*]}{.metadata.name}{'\t'}{.spec.containers[*].image}{'\n'}" | grep 'k8s/dcgm-exporter'  |  awk -F':' '{print $2}'  | sed 's/-ubuntu.*//g' 
      register: dgcm
      ignore_errors: yes

    - name: Check GPU Operator Node Feature Discovery Versions
      shell: kubectl get pods --all-namespaces -o=jsonpath="{range .items[*]}{.metadata.name}{'\t'}{.spec.containers[*].image}{'\n'}" | grep 'node-feature-discovery' | head -n1 |  awk -F':' '{print $2}'
      register: nodediscover
      ignore_errors: yes

    - name: Check GPU Operator GPU Feature Discovery Versions
      shell: kubectl get pods --all-namespaces -o=jsonpath="{range .items[*]}{.metadata.name}{'\t'}{.spec.containers[*].image}{'\n'}" | grep 'nvidia/gpu-feature-discovery'  | awk -F':' '{print $2}' | head -n1
      register: gpudiscover
      ignore_errors: yes

    - name: Check Nvidia GPU Operator versions
      shell: kubectl get pods --all-namespaces -o=jsonpath="{range .items[*]}{.metadata.name}{'\t'}{.spec.containers[*].image}{'\n'}" | grep 'nvidia/gpu-operator'  | awk -F':' '{print $2}' | head -n1
      register: gpuoperator
      ignore_errors: yes

    - name: Check Mellanox Network Operator version
      when: "enable_network_operator == true"
      shell: kubectl get pods -n network-operator -o=jsonpath="{range .items[*]}{.metadata.name}{'\t'}{.spec.containers[*].image}{'\n'}" | grep 'network-operator'  | awk -F':' '{print $2}' | head -n1
      register: networkoperator
      ignore_errors: yes

    - name: Check Mellanox MOFED Driver Version
      when: "enable_network_operator == true"
      shell: kubectl get pods -n nvidia-network-operator-resources -o=jsonpath="{range .items[*]}{.metadata.name}{'\t'}{.spec.containers[*].image}{'\n'}"  | grep mellanox/mofed | awk -F'mofed-' '{print $3}' | awk -F":" '{print $1}' | head -n1
      register: mofed_version
      ignore_errors: yes

    - name: Check RDMA Shared Device Plugin Version
      when: "enable_network_operator == true"
      shell: kubectl get pods -n nvidia-network-operator-resources -o=jsonpath="{range .items[*]}{.metadata.name}{'\t'}{.spec.containers[*].image}{'\n'}"  | grep rdma-shared | awk -F':' '{print $2}' | head -n1
      register: rdma_version
      ignore_errors: yes

    - name: Check SRIOV Device Plugin Version
      when: "enable_network_operator == true"
      shell: kubectl get pods -n nvidia-network-operator-resources -o=jsonpath="{range .items[*]}{.metadata.name}{'\t'}{.spec.containers[*].image}{'\n'}"  | grep sriov-device | awk -F':' '{print $2}' | head -n1
      register: sriov_version
      ignore_errors: yes

    - name: Check Container Networking Plugins Version
      when: "enable_network_operator == true"
      shell: kubectl get pods -n nvidia-network-operator-resources -o=jsonpath="{range .items[*]}{.metadata.name}{'\t'}{.spec.containers[*].image}{'\n'}"  | grep plugins | awk -F':' '{print $2}' | head -n1
      register: cni_version
      ignore_errors: yes

    - name: Check Multus Version
      when: "enable_network_operator == true"
      shell: kubectl get pods -n nvidia-network-operator-resources -o=jsonpath="{range .items[*]}{.metadata.name}{'\t'}{.spec.containers[*].image}{'\n'}"  | grep multus | awk -F':' '{print $2}' | head -n1
      register: multus_version
      ignore_errors: yes

    - name: Check Whereabouts Version
      when: "enable_network_operator == true"
      shell: kubectl get pods -n nvidia-network-operator-resources -o=jsonpath="{range .items[*]}{.metadata.name}{'\t'}{.spec.containers[*].image}{'\n'}"  | grep whereabouts | awk -F':' '{print $2}' | head -n1
      register: whereabouts_version
      ignore_errors: yes

    - name: check master node is up and running
      shell: kubectl get nodes | grep -i ready
      register: nodeready
      failed_when: "'NotReady' in nodeready.stdout"
      ignore_errors: yes

    - name: Check all pods are running for Kubernetes
      shell: kubectl get pods --all-namespaces | egrep -iv 'Running|NAME|Completed'
      register: kubepods
      failed_when: kubepods.rc == 0
      ignore_errors: yes

    - name: validate helm installed
      shell: helm ls
      register: helmls
      failed_when: helmls.rc == 1
      ignore_errors: yes

    - name: Validate the GPU Operator pods State
      shell: kubectl get pods --all-namespaces | egrep -v 'kube-system|NAME'
      register: pods
      failed_when: pods.rc == 1
      ignore_errors: yes

    - name: Collecting Number of GPU's
      shell: "kubectl describe nodes | grep -A 6 Capacity | grep 'nvidia.com/gpu' | awk '{print $2}' | head -n1 | tr -d '\n'"
      register: gpus
      ignore_errors: yes

    - name: Validating the nvidia-smi on Cloud Native Core
      command: "kubectl run gpu-test --rm -t -i --restart=Never --image=nvidia/cuda:11.4.0-base-ubuntu20.04 --limits=nvidia.com/gpu={{ gpus.stdout }} -- nvidia-smi"
      when: "cnc_version == 5.0 or cnc_version == 4.2"
      register: smi
      ignore_errors: yes
      async: 60

    - name: Validating the nvidia-smi on Cloud Native Core
      command: "kubectl run gpu-test --rm -t -i --restart=Never --image=nvidia/cuda:11.6.0-base-ubuntu20.04 --limits=nvidia.com/gpu={{ gpus.stdout }} -- nvidia-smi"
      when: "cnc_version == 6.0"
      register: smi
      ignore_errors: yes
      async: 60

    - name: Validating the CUDA with GPU
      shell: kubectl run cuda-vector-add --rm -t -i --restart=Never --image=k8s.gcr.io/cuda-vector-add:v0.1
      register: cuda
      ignore_errors: yes
      async: 60

    - name: Report Operating System Version of RHEL/CentOS
      when: "ansible_distribution in ['RedHat', 'CentOS']"
      ignore_errors: yes
      debug:
        msg: "RHEL/CentOS Operating System version {{ osversion.stdout }}"

    - name: Report Operating System Version of Ubuntu
      when: "ansible_distribution == 'Ubuntu'"
      ignore_errors: yes
      debug:
        msg: "Ubuntu Operating System version {{ osversion.stdout }}"

    - name: Report Docker Version
      when: cnc_version <= 3.1
      ignore_errors: yes
      debug:
        msg: "Docker Version {{ dockerversion.stdout }}"

    - name: Report Containerd Version
      when: cnc_version >= 4.0
      ignore_errors: yes
      debug:
        msg: " Containerd Version {{ containerd_version.stdout }}"

    - name: Report Kubernetes Version
      ignore_errors: yes
      debug:
        msg: "Kubernetes Version {{ k8sversion.stdout }}"

    - name: Report Helm Version
      ignore_errors: yes
      debug:
        msg: "Helm Version {{ helmversion.stdout }}"

    - name: Report Nvidia GPU Operator version 
      ignore_errors: yes
      debug:
        msg: "Nvidia GPU Operator versions {{ gpuoperator.stdout }}"

    - name: Report Nvidia Container Driver Version
      ignore_errors: yes
      debug:
        msg: "Nvidia Container Driver Version {{ nvcdriver.stdout }}"

    - name: Report GPU Operator NV Toolkit Driver
      ignore_errors: yes
      debug:
        msg: "NV Container Toolkit Version {{ nvtoolkit.stdout }}"

    - name: Report K8sDevice Plugin Version
      ignore_errors: yes
      debug:
        msg: "Nvidia K8s Device Plugin Version {{ k8sdevice.stdout }}"

    - name: Report Data Center GPU Manager (DCGM) Version
      ignore_errors: yes
      debug:
        msg: "Data Center GPU Manager (DCGM) Version {{ dgcm.stdout }}"
  
    - name: Report Node Feature Discovery Version
      ignore_errors: yes
      debug:
        msg: "Node Feature Discovery Version {{ nodediscover.stdout }}"

    - name: Report GPU Feature Discovery Version
      ignore_errors: yes
      debug:
        msg: "GPU Feature Discovery Version {{ gpudiscover.stdout }}"

    - name: Report GPU Operator Pods
      debug:
        msg: "{{ pods.stdout_lines }}"

    - name: Report Nvidia SMI Validation
      ignore_errors: yes
      debug:
        msg: "{{ smi.stdout_lines }}"

    - name: Report Cuda Validation
      ignore_errors: yes
      debug:
        msg: "{{ cuda.stdout_lines }}"

    - name: Report Network Operator version
      when: "enable_network_operator == true"
      ignore_errors: yes
      debug:
        msg: "Network Operator version {{ networkoperator.stdout }}"

    - name: Report Mellanox MOFED Driver Version
      when: "enable_network_operator == true"
      ignore_errors: yes
      debug:
        msg: "Mellanox MOFED Driver version {{ mofed_version.stdout }}"

    - name: Report RDMA Shared Device Plugin Version
      when: "enable_network_operator == true"
      ignore_errors: yes
      debug:
        msg: "RDMA Shared Device Plugin version {{ rdma_version.stdout }}"

    - name: Report SRIOV Device Plugin Version
      when: "enable_network_operator == true"
      ignore_errors: yes
      debug:
        msg: "SRIOV Device Plugin version {{ sriov_version.stdout }}"

    - name: Report Container Networking Plugin Version
      when: "enable_network_operator == true"
      ignore_errors: yes
      debug:
        msg: "Container Networking Plugin version {{ cni_version.stdout }}"

    - name: Report Multus Version
      when: "enable_network_operator == true"
      ignore_errors: yes
      debug:
        msg: "Multus version {{ multus_version.stdout }}"

    - name: Report Whereabouts Version
      when: "enable_network_operator == true"
      ignore_errors: yes
      debug:
        msg: "Container Whereabouts version {{ whereabouts_version.stdout }}"

    - name: Status Check
      shell: echo "All tasks should be changed or ok, if it's failed or ignoring means that validation task failed."
      register: check

    - debug:
        msg: "{{ check.stdout }}"
